### ISSUE TITLE
android sdk won't install during vagrant up

### ISSUE THREAD

**Issue by quentin-berlemont** [SamClayton/ionic-box#2]
Hello,

i got an error during `vagrant up`, i tried several times without success..

```
==> default: platform-tool,android-22,android-23,build-tools-22.0.1,extra
==> default: Exception in thread "main"
==> default: org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
==> default:
==> default: at org.eclipse.swt.SWT.error(Unknown Source)
==> default:
==> default: at org.eclipse.swt.widgets.Display.createDisplay(Unknown Source)
==> default:
==> default: at org.eclipse.swt.widgets.Display.create(Unknown Source)
==> default:
==> default: at org.eclipse.swt.graphics.Device.<init>(Unknown Source)
==> default:
==> default: at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
==> default:
==> default: at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
==> default:
==> default: at org.eclipse.swt.widgets.Display.getDefault(Unknown Source)
==> default:
==> default: at org.eclipse.swt.widgets.Shell.<init>(Unknown Source)
==> default:
==> default: at org.eclipse.swt.widgets.Shell.<init>(Unknown Source)
==> default:
==> default: at com.android.sdkuilib.internal.repository.ui.SdkUpdaterWindowImpl2.createShell(SdkUpdaterWindowImpl2.java:168)
==> default:
==> default: at com.android.sdkuilib.internal.repository.ui.SdkUpdaterWindowImpl2.open(SdkUpdaterWindowImpl2.java:137)
==> default:
==> default: at com.android.sdkuilib.repository.SdkUpdaterWindow.open(SdkUpdaterWindow.java:111)
==> default:
==> default: at com.android.sdkmanager.Main.showSdkManagerWindow(Main.java:413)
==> default:
==> default: at com.android.sdkmanager.Main.doAction(Main.java:369)
==> default:
==> default: at com.android.sdkmanager.Main.run(Main.java:151)
==> default:
==> default: at com.android.sdkmanager.Main.main(Main.java:117)
```

i have to `vagrant ssh` and execute manually this bash part :

```
expect -c '
set timeout -1   ;
spawn /home/vagrant/android-sdk-linux/tools/android update sdk -u --all --filter platform-tool,android-22,android-23,build-tools-22.0.1
expect { 
    "Do you accept the license" { exp_send "y\r" ; exp_continue }
    eof
}
'
```

Do you have any idea ?

Thanks !

ps: windows 10, i7, 8go and latest vagrant / virtualbox

**Comment by SamClayton** [comment]
Did you overcome this and/or issue #3 ? I haven't been using ionic lately, so I haven't had a chance to attempt to reproduce these issues.

**Comment by quentin-berlemont** [comment]
i overcome this one and #3
